spring:
  profiles:
    active: dev
---
spring:
  profiles: cloud
  redis:
    host: ${vcap.services.catalog-redis.credentials.hostname:localhost}
    port: ${vcap.services.catalog-redis.credentials.port:6379}
---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  datasource:
    #url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
    username: catalogdev
    password:
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false
